sync: google-drive pineman
		

google-drive:
	rsync -Cruv "/cygdrive/c/Users/Diogo Tito Marques/Desktop/variante_tito" "/cygdrive/c/Users/Diogo Tito Marques/Google Drive/FCUL/IPM_040/variante_tito"

pineman:
	git pull --rebase origin master
	git push origin master

fcul:
	git push fcul


